/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { LocationSegments } from '@stencil/router';

export namespace Components {
  interface ListDemo {}
  interface RouteDemo {
    location: LocationSegments;
  }
  interface TestItem {
    index: number;
  }
}

declare global {
  interface HTMLListDemoElement
    extends Components.ListDemo,
      HTMLStencilElement {}
  var HTMLListDemoElement: {
    prototype: HTMLListDemoElement;
    new (): HTMLListDemoElement;
  };

  interface HTMLRouteDemoElement
    extends Components.RouteDemo,
      HTMLStencilElement {}
  var HTMLRouteDemoElement: {
    prototype: HTMLRouteDemoElement;
    new (): HTMLRouteDemoElement;
  };

  interface HTMLTestItemElement
    extends Components.TestItem,
      HTMLStencilElement {}
  var HTMLTestItemElement: {
    prototype: HTMLTestItemElement;
    new (): HTMLTestItemElement;
  };
  interface HTMLElementTagNameMap {
    'list-demo': HTMLListDemoElement;
    'route-demo': HTMLRouteDemoElement;
    'test-item': HTMLTestItemElement;
  }
}

declare namespace LocalJSX {
  interface ListDemo {}
  interface RouteDemo {
    location?: LocationSegments;
  }
  interface TestItem {
    index?: number;
  }

  interface IntrinsicElements {
    'list-demo': ListDemo;
    'route-demo': RouteDemo;
    'test-item': TestItem;
  }
}

export { LocalJSX as JSX };

declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'list-demo': LocalJSX.ListDemo &
        JSXBase.HTMLAttributes<HTMLListDemoElement>;
      'route-demo': LocalJSX.RouteDemo &
        JSXBase.HTMLAttributes<HTMLRouteDemoElement>;
      'test-item': LocalJSX.TestItem &
        JSXBase.HTMLAttributes<HTMLTestItemElement>;
    }
  }
}
